<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CompanyRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required',
            'email' => 'nullable|email',
            'logo' => 'nullable|image|mimes:jpeg,png,jpg,gif|dimensions:min_width=100,min_height=100',
            'website' => 'nullable',
        ];
    }
    public function messages(): array
    {
        return [
            'name.required' => 'Please Enter Valid Company Name',
            'email.min' => 'Please Enter Valid Email',
            'logo.dimensions'=>'Please Select Valid Dimension Logos',
        ];

        //return parent::messages(); // TODO: Change the autogenerated stub
    }
}
